export type partnersBlockType = {
  id: number,
  titleTj: string,
  titleRu: string,
  titleEn: string,
  descriptionTj: string,
  descriptionRu: string,
  descriptionEn: string,
  slug: string,
  imagePath: string,
  site: string,
  phone: string,
  created_at: string,
  updated_at: string,
};
